[".config/wallpapers/catppuccin-mocha"]
    type = "archive"
    url = "https://github.com/orangci/walls-catppuccin-mocha/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
