[".config/wallpapers/catppuccin-mocha"]
    type = "archive"
    url = "https://github.com/orangci/walls-catppuccin-mocha/archive/master.tar.gz"
    exact = true
    stripComponents = 1

[".config/wallpapers/nord"]
    type = "archive"
    url = "https://github.com/some-user/nord-wallpapers/archive/master.tar.gz"
    exact = true
    stripComponents = 1
