exec-once = noctalia
exec-once = noctalia-shell
bind = SUPER, q, exec, kitty
bind = SUPER, h, exec, hyprmod
bind = SUPER, b,exec, brave


# HyprMod managed settings
source = /home/roehl/.config/hypr/hyprland-gui.conf

# >>> HYPRLAND VISUAL EDITOR START <<<
# 1. Active Uninstall Watchdog
exec-once = /home/roehl/.cache/noctalia/HVE/hve_watchdog.sh
# 2. Variable Definition (Color Palette)
source = /home/roehl/.config/hypr/noctalia/noctalia-colors.conf
# 3. Effects Application (Visual Editor)
source = /home/roehl/.cache/noctalia/HVE/overlay.conf
# >>> HYPRLAND VISUAL EDITOR END <<<
