[commands]
"System Configuration Backup" = "sh /home/roehl/.local/bin/cz-sync.sh"



[misc]
# We disable these because we are handling them via your custom scripts above
disable = ["firmware", "nix", "system", "containers", "spicetify", "chezmoi"]
display_time = true
assume_yes = true
